#!/bin/bash

terraform init  # initialization of terraform

terraform fmt   # apply standard formatting to tf files

terraform validate  # validate configurations

terraform plan  # view execution plan generated by terraform

terraform apply # apply configuration

docker tag express-example:latest 794038210581.dkr.ecr.eu-west-2.amazonaws.com/practice/express-example # tag the docker image with the given aws URI

docker push 794038210581.dkr.ecr.eu-west-2.amazonaws.com/practice/express-example   # push the image to the container